export default {
  donate: 'Donate',
  helpMessage: `Vot Diaspora is just one of the solutions designed and built by Code for Romania volunteers completely for free. <b>Send "PUTEM" via SMS to <a href="sms://8864?body=PUTEM">8864</a></b> to donate 4 euros per month and you too can help us in our quest to digitalize Romania by building hundreds of other equally useful solutions. For more details go to <a class="text-primary" href="https://code4.ro/putem"><b>code4.ro/putem</b></a>`,
  nav_about: 'About',
  guide_title: 'Please select the option below most suited',
  guide_text:
    'For the parliamentary elections only Romanian citizens living abroad can vote. Find out what you have to do to be able vote for the December 5th and 6th 2020 Elections in the country where you are currently residing.',
  votersGuide: {
    callToAction: 'Start by selecting one of the options below',
    label0: 'I want to vote in a precinct',
    label1: 'I want to vote by mail-in ballot',
    label10: `<p>If you have chosen to vote by mail then you will need to make sure that you have received the envelope with the necessary documents to vote. If you have not received the
envelope, contact the Permanent Electoral Authority using the contact details below.</p>
    <h4>Important:</h4>
    <p>The envelope containing your ballot must arrive back in Romania at the Mail-In Electoral
Bureau or at the diplomatic mission or consular post in the country where you reside <b> by
December 3, 2020 </b>. Given the international context generated by the COVID-19 pandemic,
consult either the postal services in your country (online or by phone) or check transport
restrictions on <a href="https://www.posta-romana.ro/a1309/stiri/lista-tarilor-cu-trafic-postal-restrictionat.html"> the Romanian Post Office website</a>.</p>
 <h4>Step 1: Checking the Documents</h4>
 <p>The envelope received (referred to in official procedures as an "outer envelope") must contain:</p>
     <ul>
       <li>A voter certificate</li>
       <li>A label used to seal the outer envelope</li>
       <li>A sticker with the address of the polling station for your ballot</li>
       <li>A second sticker with the words "Priority / Prioritaire ..."</li>
       <li>A barcode that ensures your identification as a voter</li>
       <li>A set of instructions on how to cast your vote</li>
       <li>A mail-in ballot for the Senate elections</li>
       <li>A mail-in ballot for the Chamber of Deputies elections</li>
       <li>A second envelope, the "inner envelope" that contains a support envelope that has two "VOTE" stickers on the inside and a label that you will use to seal this inner envelope</li>
    </ul>
    <h4>Important!</h4>
    <p>If you are  missing the ballots or if they have been damaged, you can print them yourself (it is not necessary to print the entire ballot, just the page with your voting preference is enough - if it has the "VOTED" sticker it will be considered a valid vote). You can download the two newsletters from the <a href="https://www.votstrainatate.ro">votstrăinatate.ro</a> website.</p>
     <p>For any problems you can contact the Permanent Electoral Authority at <a href="mailto:contact@votstrainatate.ro">contact@votstrainatate.ro</a>.</p>
    <h4>Step 2: Voting</h4>
    <p>To vote you must:</p>
    <ol>
      <li>Open the two ballots: for the Senate elections and for theChamber of Deputies elections</li>
      <li>Identify your voting options on each of the two documents and stick the "VOTED" stickers next to them</li>
      <li>Insert the two ballot papers into the inner envelope and seal it with the appropriate label. (Detailed visual instructions <a href="https://votstrainatate.ro/Uploads/MACHETA_INSTRUCTIUNI_VC.pdf">can be found here</a>)</li>
    </ol>
    <h4>Step 3: Mail-in your vote</h4>
    <p>After sealing the inner envelope, fill in the voter certificate with the date and signature. Then:</p>
    <ol>
      <li>Insert the voter certificate and the sealed inner envelope in the outer envelope. It is very important not to forget the voter certificate because otherwise your vote will be considered invalid</li>
      <li>Seal the outer envelope by applying the safety label on the back (Detailed visual instructions <a href="https://votstrainatate.ro/Uploads/MACHETA_INSTRUCTIUNI_VC.pdf">can be found here</a>)</li>
      <li>The sticker with the address of the mail-in ballot electoral bureau must also be applied on the back of the envelope</li>
      <li>Drop the envelope at any post office or mailbox free of charge. Optionally, you can send the envelope with a courier at your own expense</li>
    </ol>
    <h4>Note:</h4>
    <p>If for any reason you do not want to mail the envelope to Romania, directly to the electoral office for mail-in voting, you can send it by courier or deposit it at the nearest Romanian diplomatic mission or consular office in your country of residence. It is important for the envelope to reach itsdestination <b>by December 3, 2020</b>.</p>`,
    label11: 'I was registered in the Electoral Register in 2020',
    label111: ' (domicile)',
    label1110: `<p>If you have registered in the Electoral Register and you are domiciled abroad then you will vote on the permanent list at the polling station where your municipality is allotted.</p>
    <h4>Documents required:</h4>
    <p>In order to be able to vote, you must have one of the following identity documents:</p>
    <ul>
      <li>simple passport, with  country of residence mentioned within</li>
      <li>temporary simple passport, with the country of residence mentioned within</li>
      <li>simple electronic passport, with the country of residence mentioned within</li>
    </ul>
    <h4>The program is as follows:</h4>
    <p>Voting abroad will take place over two days.</p>
    <ul>
      <li>Saturday, December 5, between 7.00 (local time) and 21.00 (local time)</li>
      <li>Sunday, December 6, between 7.00 (local time) and 21.00 (local time) with the
possibility of extending the voting until 23.59 local time if there still are voters in the polling
station or in a row outside the polling station waiting to enter the polling station to vote</li>
    </ul>
    <h4>Important</h4>
    <ul>
      <li>If you are not on the permanent list due to an error or because you have not confirmed your registration, you will be still able to vote on additional lists.</li>
      <li>If you can no longer go to the polling station in the municipality stated as the place where you live when you registered, you will still be able to vote on additional lists if you prove that you have your domicile or residence abroad.</li>
    </ul>
    `,
    label112: 'I reside abroad (residence)',
    label1120: `<p>If you have registered in the Electoral Register and you reside abroad then you will vote on the permanent lists at the polling station where your municipality is allotted.</p>
<h4>Required Documents:</h4>
    <p>In order to vote you need the following two documents:</p>
    <ul>
      <li>An <b>identity document</b>: identity card, electronic identity card, provisional identity
card, identity booklet, diplomatic passport, electronic diplomatic passport, service passport,
electronic service passport, simple passport, simple electronic passport or temporary simple
passport.</li>
      <li>An official <b> document </b> issued by the foreign state <b>stating your residence</b>. You can consult the <a
href="https://www.mae.ro/sites/default/files/file/anexa_omae_1627_20191_cu_anexe.pdf">list
of documents certifying residence abroad by accessing this link</a>. Accepted documents
differ from country to country.</li>
    </ul>
    <h4>The program is as follows:</h4>
    <p>Voting abroad will take place over two days.</p>
    <ul>
      <li>Saturday, December 5, between 7:00 a.m. (local time) and 9:00 p.m. (local time).</li>
      <li>Sunday, December 6, between 7.00 (local time) and 21.00 (local time) with the
possibility of extending the voting until 23.59 local time if there still are voters in the polling
station or in a row outside the polling station waiting to enter the polling station of vote.</li>
    </ul>
    <h4>Important </h4>
    <ul>
      <li>If you are not on the permanent list due to an error or because you have not confirmed
your registration, you will be able to vote on additional lists.</li>
      <li>If you can no longer appear at the polling station in the locality declared for registration
in the Electoral Register, you will be able to vote on additional lists if you prove that you have
your domicile or residence abroad.</li>
    </ul>
    `,
    label12: 'I did not register in the Electoral Register in 2020',
    label121: 'I live abroad (domicile)',
    label1210: `<p>If you have not registered in the Electoral Register and are domiciled abroad
then you will vote on additional lists.</p>
    <h4>Documents required:</h4>
    <p>In order to be able to vote, you must have one of the following identity documents:</p>
    <ul>
      <li>simple passport, with the country of residence mentioned</li>
      <li>temporary simple passport, with the country of residence mentioned</li>
      <li>simple electronic passport, with the country of residence mentoned</li>
    </ul>
    <h4>The schedule is as follows:</h4>
    <p>Voting abroad will take place over two days.</p>
    <ul>
      <li>Saturday, December 5, between 7.00 (local time) and 21.00 (local time)</li>
      <li>Sunday, December 6, between 7.00 (local time) and 21.00 (local time) with the
possibility of extending the voting until 23.59 local time if there are still voters in the polling
station or in a row outside the polling station to enter the polling station of vote</li>
    </ul>`,
    label122: 'I reside abroad (residence)',
    label1220: `<p>If you have not registered in the Electoral Register and reside abroad then
you will vote on additional lists.
    <h4>Documents required:</h4>
    <p>In order to vote you need the following two documents:</p>
    <ul>
      <li>An <b> identity document </b>: identity card, electronic identity card, provisional identity
card, identity booklet, diplomatic passport, electronic diplomatic passport, service passport,
electronic service passport, simple passport, simple electronic passport or temporary simple
passport.</li>
      <li>An official <b>document</b> issued by the foreign state <b>as proof of residence</b>. You can consult the <a href="https://www.mae.ro/sites/default/files/file/anexa_omae_1627_20191_cu_anexe.pdf">list
of documents certifying residence abroad by accessing this link</a>. Accepted documents
differ from country to country.</li>
    </ul>
    <h4>The schedule is as follows:</h4>
    <p>Voting abroad will take place over two days.</p>
    <ul>
      <li>Saturday, December 5, between 7:00 a.m. (local time) and 9:00 p.m. (local time).</li>
      <li>Sunday, December 6, between 7.00 (local time) and 21.00 (local time) with the
possibility of extending the voting until 23.59 local time if there are still voters in the polling
station or in a row outside the polling station waiting to enter the polling station of vote.</li>
    </ul>
    `,
  },
  pollingStationSearch: {
    question: 'Where do you live?',
    callToAction:
      '<p>Look for the town or city where you live to find your closest polling station. Any map search on this platform incurs extra costs for us. If Vot Diaspora is of help to you consider <a target="_blank" rel="noopener" href="https://code4.ro/ro/doneaza/">donating</a> if you can to Code for Romania, the NGo that developed this site completely pro bono.</p>',
    searchPlaceholder:
      'Search for your address to find the polling station where you are registered to vote',
    hasPermanentResidence:
      'The address  you are looking for is registered at the following polling station:',
  },
  pollingStationCard: {
    distance: 'Distance:',
    seeStreets: 'See Street List',
    pollingStationNumber: 'Polling Station No.',
    address: 'Address:',
    assignedStreetsLabel:
      'People who reside on the following streets can vote at this polling station:',
  },
  back_button: 'Back',
  back_to_start_button: 'Back to start',
  introduction:
    'On the 6th of December 2020  parliamentary elections will be held  in Romania. Romanian citizens living abroad can vote at polling stations or through mail-in ballots. To find out what the required steps are so that you can cast a ballot in the elections use the guide below.',
  about: {
    title: 'About the Project',
    text: `<p>Vot Diaspora is a platform that simplifies the electoral guide for the 6th of December elections for citizens. Vot Diaspora is Code for Romania's first ever project, starting with 2016, in order to facilitate access to electoral information for Romanians abroad and foster a more transparent process. 25% of all voters abroad used the app for the 2019 European Parliament elections and over 185.000 voters used it at the 2019 presidential elections.</p>  <p>By accessing votdiaspora.ro, all citizens can check the required documents for voting, the correct procedures for voting either at polling stations or via mail-in ballot and their alotted polling station and the closest route. The Website will be available and updated for each new round of elections. All content available on the Vot Diaspora platform is done in collaboration with Observatorul Electoral electoral experts. </p><p>Vot Diaspora is part of Code for Romania's electoral ecosystem, and is the fourth app dedicated to the electoral process in our country. Monitorizare Vot is the web and mobile app dedicated to independent electoral observers, the first such app in Romania and the most used app at a global level. Launched in 2016, this has been used for every election or referendum since 2016 and has been used in Poland in 2018 for the first monitored elections in the country. The second app in the ecosystem is Vot Romania, a web app designed for Romanians living in the country, showing them where they can vote and what the correct documents and procedures for voting are. The third app is Rezultate Vot, website launched in 2019 to show real time participation and vote count data that has, since 2020 become a repository of all post-1990 electoral data as well as other features, turning it into a good comparative data tool as well. </p><p> All election related apps are developed by Code for Romania volunteers as part of our <a href="https://civiclabs.ro/en” rel="noreferrer" target="_blank">Civic Labs</a>, program, one of the programs through which we develop civic tech solutions for issues in 6 key areas - education,  health, environment, vulnerable groups, transparency and civic engagement. </p><p > Code for Romania is a non-profit organization developing digital solutions for social problems on a pro-bono basis. Founded in 2016 Code for Romania has over 1700 volunteers from IT fields who have developed dozens of web and mobile apps, including ROmania's Covid-19 information ecosystem, <a href="https://stirioficiale.ro">știrioficiale.ro</a>, <a href="https://rohelp.ro">rohelp.ro</a>, <a href="https://redirectioneaza.ro">redirectioneaza.ro</a> și altele..</p>`,
    p1: 'This solution was prototyped in:',
    p2: 'developed pro-bono by:',
    p3: 'in partnership with:',
  },
  info_text:
    'On the 6th of December 2020  parliamentary elections will be held  in Romania. Romanian citizens living abroad can vote at polling stations or through mail-in ballots. To find out what the required steps are so that you can cast a ballot in the elections use the guide below',
  map_text: `<p class=“font-weight-bold m-0”>There will soon be a map and a search bari right here, helping you identify your polling station.<br/> If this website was helpful please <a
    href=“https://code4.ro/ro/doneaza/”
    target=“_blank”
    rel=“noopener noreferrer”>donate as little or as much as you can</a> to Code for Romania, the NGO that developed this website pro bono.</p>`,
  temp_text:
    'The current polling station map is the one used for the 2019 presidential elections. The map will be updated as the new list of polling stations becomes abvailable .The Permanent Electoral Authority has to submit the final list of foreign municipalities where polling places will be organized to the Foreign Ministry by September 25th 2020 at the latest.',
  social_share: {
    title: 'Send this to your friends',
    text:
      'Share this on social media to help as many Romanians as possible know where they can vote at the 2020 parliamentary elections, what documents they need and other useful advice.',
  },
  donate_card: {
    title: 'Support Us',
    text:
      'Vot Diaspora is a project developed completely pro bono by a team of Code for Romania volunteers. Every day, hundreds of our friends and colleagues are working to create useful digital tools to make all our lives easier, and to help bring Romania closer to technological progress. Help us continue.',
  },
  cookie: {
    title: 'Confidentiality Policy',
    text: `<p>This website uses cookies in order to provide users with a better browsing experience as well as services tailored to their needs and interests.</p>
    <p>Cookies are used to facilitate access and delivery for the services required by Internet users such as personalizing settings (language, country, prices displayed in local currency etc.) Cookies, based on the information about users that they gather, help operators make their websites more effective so that they can be easier to access by users. They also make online advertising more effective and can help multimedia apps and content from other websites be more easily embedded, to make navigation easier.</p>
    <h2>What is a Cookie?</h2>
    <p>Cookie (browser cookie or HTTP cookie) is a small file, a succession of letters and numbers, that is stored on any terminal with Internet access (computers, mobile phones, tablets etc.) and is installed upon a request from a server to a browser (ex: Internet Explorer, Chrome). Cookies do not contain any software programs, viruses or spyware and cannot access information on the user’s hard drive.</p>
    <p>Cookie consists of a name and content, the length of its existence is limited, and it can be accessed again by the webserver when a user returns to the website associated with that server.</p>
    <p>Cookies do not request personal information nor do they personally identify internet users.</p>
    <p>Session cookies - are cookies temporarily stored in the browser’s history where they are stored until the user leaves that website or closes the browser window.</p>
    <p>Persistent Cookies - These are stored, for a predetermined length of time, on a computer hard drive or similar equipment. Persistent cookies include those placed by a different website than the one the user is visiting at the time, so-called third-party cookies- that can be anonymously used to track a user’s interests - allowing them to receive ads more relevant to their interests.</p>
    <h2>What are the advantages of Cookies?</h2>
    <p>A cookie contains information that connects users to a specific website. If a browser accesses the same server again it can read the information already stored in the cookie and react accordingly.</p>
    <h2>What is the average lifespan of a cookie?</h2>
    <p>There are cookies that are exclusively used for a single session - these are no longer stored after the user has left the website. Permanent cookies are stored and reused every time the user returns to that website but can be deleted at any time by the user.</p>
    <h2>What are third party cookies?</h2>
    <p>Some parts of the content or services on the accessed website can be placed there by third parties via banners, boxes or links - and all these instruments can contain cookies. These are called third-party cookies because they are not placed by the owner of the respective website, third party cookies do however have to abide by the law and by the site owner’s confidentiality policy.</p>
    <h2>How does this website use cookies?</h2>
    <p>Upon visiting this website you may receive the following cookie types:</p>
    <ul>
      <li>Cookies used for finalizing your donation</li>
      <li>Cookies that are used to analyse general user data</li>
      <li>Registration cookies</li>
      <li>Some cookies can be third-party cookies.</li>
    </ul>
    <h2>Cookies used for finalizing your donation</h2>
    <p>Filling out the donation form consists of several steps. In order to follow up with a donor and offering them the needed documentation we will save a cookie that offers us a way to identify that donor (like a ticket). Every time the form is filled a new cookie is created or the existing one is overwritten.</p>
    <h2>Cookies that are used to analyse general user data</h2>
    <p>Every time I use your visit this website the analytics software provided by a third-party generates a cookie used to analyze the user profile. Cookie tells us if you've ever visited this website before. The browser will let us know if you have this cookie installed, and if not, this cookie is generated. This allows us to Monitor the number of unique users visiting this website as well as how often they return. This cookie cannot be used to identify physical persons and it is only used for statistical purposes.</p>
    <h2>Registration cookies</h2>
    <p>When registering to this website, we generate a cookie with your registration data. The cookie helps us in the next steps for communicating with the server. It is possible for this cookie to remain on your device if you do not follow through with all the registration steps. However, this cookie will be overwritten the next time you attempt to register on this website.</p>
    <h2>Other third party cookies</h2>
    <p> On some pages third parties can SET "ResolvedAddressStatus" = 2,up their own anonymous cookies for purposes of tracking an app’s success rate, or for customizing that app. Due to the way it is used, this website cannot access these cookies, just as third parties cannot access the cookies that belong to this website. For example when you share a page using a “share to social network” button on this website, that social network can track your activity. </p>
    <h2>What kind of information is stored and accessed through cookies?</h2>
    <p>Cookies save information in a small text file allowing a website to recognize a browser. The web server will recognize the browser up until the cookie expires or is deleted. The cookie stores important information that improve the browsing experience (e.g. a serial number for your donation)</p>
    <h2>Why are cookies important to the Internet?</h2>
    <p>Cookies are one of the most important tools for a seamless, efficient Internet experience, helping to generate friendly browsing experiences tailored to the needs of every user. Refusing to accept cookies or deactivating them can make some websites impossible to use.</p>
    <p>Refusing to accept cookies or deactivating them does not mean that you will no longer receive online ads, only that these ads will no longer take your interests or preferences into account as determined by your browsing behavior.</p>
    <h2>Security and confidentiality concerns</h2>
    <p>Cookies are NOT viruses! They use plain text formats. They do not contain code strings and therefore cannot be triggered remotely nor can they activate themselves. They cannot duplicate or self-replicate across networks. As they cannot do any of the above that cannot be considered viruses.</p>
    <p> However, some cookies can be used for bad purposes. As they can store user preferences and navigation history, both from a specific website and for a broad selection of sites, cookies can be used as a form of spyware. Many anti-spyware products know this and constantly mark cookies to be deleted as part of anti-virus or anti-spyware scans. </p>
    <p>Most browsers have privacy settings allowing you to select the types of cookies to accept, their duration as well as auto-delete features that remove cookies once the user has visited a certain site.</p>
    <h2>Other Cookie security aspects</h2>
    <p>As identity protection is very important and represents the right of every internet user, it is important for you to know what potential problems may be caused by cookies. Because cookies are used to constantly transmit information both ways between the browser and the website, unauthorised persons looking to compromise your security may intercept the information contained by cookies. Although this is very rare it can happen if your browser accesses the website by using an unencrypted network (e.g. an unsecured Wifi network).</p>
    <p>Other cookie-based attacks use wrong cookie settings on servers. If a website does not ask the browser to use encrypted channels only, attackers can use this vulnerability to trick browsers into sending information via unencrypted channels. Attackers then use this information to access unauthorised websites. It is very important to take great care in choosing the right methods of protecting your personal information.</p>
    <h2>Advice for safe and responsible cookie-based browsing</h2>
    <p>To the flexibility and the fact that the majority of the largest and most visited websites use cookies, they are inevitable. Deactivating cookies will no longer allow user access to some of the most important websites such as Youtube, Gmail, Yahoo and others. Here's some advice that can help you browse safely while retaining cookies:</p>
    <ul>
      <li>Customize your browser cookie settings to allow for a comfortable security level. If cookies are not a problem for you and you are the only person using that device you can SET "ResolvedAddressStatus" = 2,long cookie retention intervals in order to store your browsing history and your personal access data. If you share the device or computer you may want to SET "ResolvedAddressStatus" = 2,up the browser to delete your individual browsing data every time it is closed. This is one way to access websites that place cookies on your shared computer while deleting all your browsing data when closing the session.</li>
      <li>Install an anti-spyware app and keep it up-to-date</li>
      <li>Many anti-spyware apps include website attack detection. These apps prevent the browser from accessing websites that might exploit the browser’s vulnerabilities or download dangerous software. Ensure your browser is up-to-date. Many cookie-based attacks exploit the weak points of old browser versions.</li>
      <li>Cookies are everywhere and cannot be avoided if you wish to access some of the largest and best websites on the internet, either local or international. The clear understanding of the way cookies work and the benefits they bring you can take the necessary security measures so that you always have a safe and satisfactory browsing experience.</li>
    </ul>
    <h2>How can I turn cookies off?</h2>
    <p>Refusing to accept cookies or deactivating them can make some websites difficult or impossible to navigate or use. Refusing to accept cookies also does not mean that you will no longer receive online ads. </p>
    <p>You can SET "ResolvedAddressStatus" = 2,up your browser to reject cookies automatically or you can select only some websites where cookies are enabled. But, for example, if you turn off cookies on this website you can not follow through with the next steps in filling out the form.</p>
    <p>Modern browsers offer the ability to change cookie settings. You can usually find cookie settings under the “options” tab or the “preferences” menu of your browser.</p>
    <p>For third-party cookies settings and for more information about online ad confidentiality, IAB Romania offers the following website: <a href="http://www.youronlinechoices.com/en/">http://www.youronlinechoices.com/en/</a></p>
    `,
  },
}
